config/routes.rb
Rails.application.routes.draw do
  resources :entries

  # Root path
  root "entries#index"

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :title, presence: true
  validates :date, presence: true
  validates :category, presence: true
  validates :body, presence: true

  def reading_time
    words_per_minute = 200.0
    text_body = self.body
    word_count = text_body.split.size
    reading_time_in_minutes = (word_count / words_per_minute).ceil
    reading_time_in_minutes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
    @entry.increment!(:click)
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:title, :date, :category, :description, :name, :body, :click)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_featured.html.erb
<div id="<%= dom_id(entry) %>" class="flex flex-col max-width mx-auto mb-[3.5rem] sm:mb-[5.625rem] gap-3 id="<%= dom_id entry %>">
  <section>
    <h3 class="flex items-center font-medium text-sm text-indigo-800 tracking-widest pb-3 gap-2"><%= entry.category.upcase %></h3>
    <%= link_to entry do %>
    <h1 class="font-vesterbro-bold font-light leading-6 tracking-tight text-xl pb-3 sm:text-4xl hover:text-indigo-800"><%= entry.title %></h1>
    <% end %>
  </section>
  <section class="flex items-center justify-center bg-gray-100 border min-w-[10rem] min-h-[15rem] sm:min-w-[13rem] sm:min-h-[10rem]">
    <% case entry.category %>
    <% when 'Health' %>
        <%= image_tag("health") %>
    <% when 'Entertainment' %>
        <%= image_tag("entertainment") %>
    <% when 'Finance' %>
        <%= image_tag("finance") %>
    <% when 'Personal' %>
        <%= image_tag("personal") %>
    <% when 'Travel' %>
        <%= image_tag("travel") %>
    <% when 'Education' %>
        <%= image_tag("education") %>
    <% when 'Food and Drinks' %>
        <%= image_tag("food") %>
    <% when 'Lifestyle' %>
        <%= image_tag("lifestyle") %>
    <% when 'Technology' %>
        <%= image_tag("technology") %>
    <% end %>
  </section>
  <section>
    <h2 class="tracking-wide pb-3"><%= entry.description %></h2>
    <span class="flex text-stone-400 text-sm tracking-widest gap-3">
      <p><%= fa_icon "eye", class: "mr-2"%><%= entry.click %> VIEW</p>
      <p><%= fa_icon "user", class: "mr-2"%><%= entry.name.upcase %></p>
    </span>
  </section>
</div>

app/views/entries/_form.html.erb
<section class="z-20 h-full flex flex-col justify-center w-full bg-gray-300 p-6 shadow transition-all duration-500 lg:h-fit lg:rounded-lg lg:m-10 lg:mx-auto lg:w-2/3">
<%= form_with(model: entry, class: "contents") do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-2">
    <%= link_to "#", data: { controller: "modals", action: "modals#close"}, class: "sticky left-[58rem] text-xl text-gray-500 hover:text-red-400" do %>
      <%= fa_icon "times" %>
    <%end %>
  </div>
  <div class="mb-4 lg:mb-8">
    <%= form.text_field :title, placeholder: "Title", class: "border border-gray-200 py-4 mt-6 border-none focus:border-transparent focus:ring-0 w-full" %>
  </div>


  <div class="flex flex-col gap-4 mb-4 lg:mb-8 lg:flex-row transition-all duration-500">
    <%= form.date_field :date, class: "border-none focus:border-transparent focus:ring-0 w-full" %>
    <%= form.select :category, options_for_select(['Health', 'Finance', 'Entertainment', 'Personal', 'Travel', 'Education', 'Food and Drinks', 'Lifestyle', 'Technology'], selected: entry.category), {}, class: "border-none focus:border-transparent focus:ring-0 w-full" %>
    <%= form.text_field :name, placeholder: "Name (Optional)", class: "border-none focus:border-transparent focus:ring-0 w-full" %>
  </div>


  <div class="mb-4 lg:mb-8 transition-all duration-500">
    <%= form.text_area :description, placeholder: "Description", rows: 2, class: "resize-none border-none focus:border-transparent focus:ring-0 w-full" %>
  </div>

  <div class="mb-4">
    <%= form.text_area :body, rows: 8, placeholder: "Body", class: "resize-none border-none focus:border-transparent focus:ring-0 w-full overflow-scroll" %>
  </div>

    <div class="flex justify-end">
      <%= form.submit class: "rounded-sm py-3 px-5 bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
  </div>
</section>

app/views/entries/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="fixed inset-0 z-30">
    <div class="absolute w-full h-screen bg-gray-100 opacity-40"></div>
    <div class="relative h-full rounded-lg">
      <%= render "form", entry: @entry %>
    </div>
  </div>
<% end %>

app/views/entries/index.html.erb
<main class="h-screen">
  <div class="fixed top-0 w-full bg-white shadow-md z-10">
    <%= render "partials/home_nav"%>
  </div>
  <% if notice.present? %>
    <p id="notice"><%= notice %></p>
  <% end %>
  <% content_for :title, "Entries" %>
  <div class="max-w-[57rem] mx-auto pt-28 overflow-y-scroll" id="entries">
    <% @entries.each_with_index do |entry, index| %>
      <% if (index - 1) % 4 == 0 %>
        <%= render partial: 'entries/featured', locals: { entry: entry } %>
      <% else %>
        <%= render entry %>
      <% end %>
      <p></p>
    <% end %>
  </div>
</main>

app/views/entries/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="fixed inset-0 z-30">
    <div class="absolute w-full h-screen bg-gray-100 opacity-40"></div>
    <div class="relative h-full rounded-lg">
      <%= render "form", entry: @entry %>
    </div>
  </div>
<% end %>

app/views/entries/show.html.erb
<main class="">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render "partials/show_entry" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scribe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= turbo_frame_tag "modal" %>
      <%= yield %>
  </body>
</html>

app/views/partials/_home_nav.html.erb
<header class="z-10 flex justify-between items-center h-[4.25rem] text-xl px-7">
    <span>
        <%= link_to "#", class: "hover-text" do %>
            <%= fa_icon "bars", class: "h-8 w-8 p-1 rounded-sm hover:bg-gray-100" %>
            <span class="tooltip-text" id="top" aria-label="Menu">Menu</span>
        <% end %>
        <%= link_to "#", class: "hover-text ml-3" do %>
            <%= fa_icon "search", class: "h-8 w-8 p-1 rounded-sm hover:bg-gray-100" %>
            <span class="tooltip-text" id="top" aria-label="Search">Search</span>
        <% end %>
    </span>
    <span class="flex items-center gap-2">
        <% if @entry %>
        <%= link_to entries_path, class: "hover-text" do %>
        <svg class="h-8 w-8 px-1 rounded-sm hover:bg-yellow-200" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#000000" stroke-width="0.648"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M4 10L3.29289 10.7071L2.58579 10L3.29289 9.29289L4 10ZM21 18C21 18.5523 20.5523 19 20 19C19.4477 19 19 18.5523 19 18L21 18ZM8.29289 15.7071L3.29289 10.7071L4.70711 9.29289L9.70711 14.2929L8.29289 15.7071ZM3.29289 9.29289L8.29289 4.29289L9.70711 5.70711L4.70711 10.7071L3.29289 9.29289ZM4 9L14 9L14 11L4 11L4 9ZM21 16L21 18L19 18L19 16L21 16ZM14 9C17.866 9 21 12.134 21 16L19 16C19 13.2386 16.7614 11 14 11L14 9Z" fill="#33363F"></path> </g></svg>
        <span class="tooltip-text" id="top">Back</span>
        <% end %>
        <% end %>
        <%= link_to new_entry_path, data: {turbo_frame: "modal"}, class: "hover-text" do %>
        <svg class="h-8 w-8 px-1 rounded-sm hover:bg-green-200" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#000000" stroke-width="0.312"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill-rule="evenodd" clip-rule="evenodd" d="M19.186 2.09c.521.25 1.136.612 1.625 1.101.49.49.852 1.104 1.1 1.625.313.654.11 1.408-.401 1.92l-7.214 7.213c-.31.31-.688.541-1.105.675l-4.222 1.353a.75.75 0 0 1-.943-.944l1.353-4.221a2.75 2.75 0 0 1 .674-1.105l7.214-7.214c.512-.512 1.266-.714 1.92-.402zm.211 2.516a3.608 3.608 0 0 0-.828-.586l-6.994 6.994a1.002 1.002 0 0 0-.178.241L9.9 14.102l2.846-1.496c.09-.047.171-.107.242-.178l6.994-6.994a3.61 3.61 0 0 0-.586-.828zM4.999 5.5A.5.5 0 0 1 5.47 5l5.53.005a1 1 0 0 0 0-2L5.5 3A2.5 2.5 0 0 0 3 5.5v12.577c0 .76.082 1.185.319 1.627.224.419.558.754.977.978.442.236.866.318 1.627.318h12.154c.76 0 1.185-.082 1.627-.318.42-.224.754-.559.978-.978.236-.442.318-.866.318-1.627V13a1 1 0 1 0-2 0v5.077c0 .459-.021.571-.082.684a.364.364 0 0 1-.157.157c-.113.06-.225.082-.684.082H5.923c-.459 0-.57-.022-.684-.082a.363.363 0 0 1-.157-.157c-.06-.113-.082-.225-.082-.684V5.5z" fill="#000000"></path></g></svg>
        <span class="tooltip-text" id="top">New</span>
        <% end %>
        <% if @entry %>
        <%= link_to edit_entry_path(@entry), data: {turbo_frame: "modal"}, class: "hover-text" do %>
        <svg class="h-8 w-8 px-1 rounded-sm hover:bg-blue-200" viewBox="0 -0.5 21 21" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <title>edit_text_bar [#1373]</title> <desc>Created with Sketch.</desc> <defs> </defs> <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> <g id="Dribbble-Light-Preview" transform="translate(-339.000000, -800.000000)" fill="#000000"> <g id="icons" transform="translate(56.000000, 160.000000)"> <path d="M286.15,654 C285.5704,654 285.1,653.552 285.1,653 L285.1,647 C285.1,646.448 285.5704,646 286.15,646 C286.7296,646 287.2,645.552 287.2,645 C287.2,644.448 286.7296,644 286.15,644 L285.1,644 C283.93975,644 283,644.895 283,646 L283,654 C283,655.105 283.93975,656 285.1,656 L286.15,656 C286.7296,656 287.2,655.552 287.2,655 C287.2,654.448 286.7296,654 286.15,654 M301.9,644 L294.55,644 C293.9704,644 293.5,644.448 293.5,645 C293.5,645.552 293.9704,646 294.55,646 L300.85,646 C301.4296,646 301.9,646.448 301.9,647 L301.9,653 C301.9,653.552 301.4296,654 300.85,654 L294.55,654 C293.9704,654 293.5,654.448 293.5,655 C293.5,655.552 293.9704,656 294.55,656 L301.9,656 C303.06025,656 304,655.105 304,654 L304,646 C304,644.895 303.06025,644 301.9,644 M293.5,659 C293.5,659.552 293.0296,660 292.45,660 L288.25,660 C287.6704,660 287.2,659.552 287.2,659 C287.2,658.448 287.6704,658 288.25,658 L289.3,658 L289.3,642 L288.25,642 C287.6704,642 287.2,641.552 287.2,641 C287.2,640.448 287.6704,640 288.25,640 L292.45,640 C293.0296,640 293.5,640.448 293.5,641 C293.5,641.552 293.0296,642 292.45,642 L291.4,642 L291.4,658 L292.45,658 C293.0296,658 293.5,658.448 293.5,659" id="edit_text_bar-[#1373]"> </path> </g> </g> </g> </g></svg>
        <span class="tooltip-text" id="top">Edit</span>
        <% end %>
        <%= link_to @entry, method: :delete, class: "hover-text" do %>
        <svg class="h-8 w-8 px-1 rounded-sm hover:bg-red-200" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g clip-path="url(#clip0_429_11026)"> <path d="M6 7V19C6 20.1046 6.89543 21 8 21H16C17.1046 21 18 20.1046 18 19V7" stroke="#292929" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M4 7H20" stroke="#292929" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M7 7L9 3H15L17 7" stroke="#292929" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"></path> </g> <defs> <clipPath id="clip0_429_11026"> <rect width="24" height="24" fill="white"></rect> </clipPath> </defs> </g></svg>
        <span class="tooltip-text" id="top">Delete</span>
        <% end %>
        <% end %>
    </span>
</header>

app/views/partials/_show_entry.html.erb
<div class="fixed top-0 w-full bg-white shadow-md z-10">
    <%= render "partials/home_nav"%>
</div>
<div class="pt-[4.25rem] sm:pt-0">
    <% case @entry.category %>
    <% when 'Health' %>
        <%= image_tag("health") %>
    <% when 'Entertainment' %>
        <%= image_tag("entertainment") %>
    <% when 'Finance' %>
        <%= image_tag("finance") %>
    <% when 'Personal' %>
        <%= image_tag("personal") %>
    <% when 'Travel' %>
        <%= image_tag("travel") %>
    <% when 'Education' %>
        <%= image_tag("education") %>
    <% when 'Food and Drinks' %>
        <%= image_tag("food") %>
    <% when 'Lifestyle' %>
        <%= image_tag("lifestyle") %>
    <% when 'Technology' %>
        <%= image_tag("technology") %>
    <% end %>
</div>
<div class="lg:relative lg:-top-12 w-full lg:max-w-[50rem] mx-auto transition-all duration-500">
    <% case @entry.category %>
    <% when 'Health' %>
        <% section_color = "bg-red-800" %>
    <% when 'Entertainment' %>
        <% section_color = "bg-yellow-800" %>
    <% when 'Finance' %>
        <% section_color = "bg-green-800" %>
    <% when 'Personal' %>
        <% section_color = "bg-blue-800" %>
    <% when 'Travel' %>
        <% section_color = "bg-green-800" %>
    <% when 'Education' %>
        <% section_color = "bg-indigo-800" %>
    <% when 'Food and Drinks' %>
        <% section_color = "bg-orange-800" %>
    <% when 'Lifestyle' %>
        <% section_color = "bg-pink-800" %>
    <% when 'Technology' %>
        <% section_color = "bg-gray-800" %>
    <% end %>
    <section class="text-white text-center <%= section_color %> p-12 mb-12">
        <h1 class="text-sm tracking-widest pb-8"><%= @entry.category.upcase %></h1>
        <h1 class="text-3xl font-vesterbro-bold pb-8 transition-all duration-500 lg:text-5xl"><%= @entry.title %></h1>
        <h1 class="text-base opacity-75 pb-8 transition-all duration-500 lg:text-2xl"><%= @entry.description %></h1>
        <span class="flex flex-col justify-center items-center text-sm tracking-widest gap-4 transition-all duration-500 lg:flex-row">
            <span class="flex gap-2">
            <p class="mr-2"><%= fa_icon "user", class: "mr-2" %><%= @entry.name.upcase %></p>
            <p><%= fa_icon "calendar", class: "mr-2" %><%= @entry.date.strftime("%d %b, %Y").upcase %></p>
            </span>
            <span class="flex gap-2">
            <p class="mr-2"><%= fa_icon "eye", class: "mr-2" %><%= @entry.click %> VIEW</p>
            <p><%= fa_icon "clock-o", class: "mr-2" %><%= @entry.reading_time %> MINS</p>
            </span>
        </span>
    </section>
    <section class="mx-12">
        <p class="font-vesterbro text-[16px] transition-all duration-500 lg:text-[21px]"><%= @entry.body %></p>
    </section>
</div>